const { GoogleGenAI } = require('@google/genai');
const fs = require('fs');
const path = require('path');
const axios = require('axios'); // For placeholder generation if needed
const https = require('https');

// We have 3 keys for rotation
const apiKeys = [
  process.env.GEMINI_API_KEY_1,
  process.env.GEMINI_API_KEY_2,
  process.env.GEMINI_API_KEY_3
].filter(Boolean);

let currentKeyIndex = 0;

function getNextClient() {
  if (apiKeys.length === 0) {
    throw new Error('No Gemini API keys found in environment variables.');
  }
  const key = apiKeys[currentKeyIndex];
  currentKeyIndex = (currentKeyIndex + 1) % apiKeys.length;
  // Initialize SDK
  return new GoogleGenAI({ apiKey: key });
}

// Convert local file to generative part
function fileToGenerativePart(filePath, mimeType) {
  return {
    inlineData: {
      data: Buffer.from(fs.readFileSync(filePath)).toString("base64"),
      mimeType
    },
  };
}

async function generateImage(prompt, outputPath) {
  try {
    const ai = getNextClient();
    // Use Imagen 3.0 via Gemini API (if available on the key)
    const response = await ai.models.generateImages({
        model: 'imagen-3.0-fast-generate-001',
        prompt: prompt,
        config: {
            numberOfImages: 1,
            outputMimeType: 'image/jpeg',
        }
    });

    if (response && response.length > 0 && response[0].imageBytes) {
        const base64Image = response[0].imageBytes;
        fs.writeFileSync(outputPath, Buffer.from(base64Image, 'base64'));
        return true;
    } else {
        throw new Error('No image generated by Gemini.');
    }
  } catch (error) {
    console.error('Gemini image generation failed, falling back to placeholder...', error.message);
    try {
        console.log('Gemini generation failed, trying Pollinations...');
        const pollinationUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?nologo=true`;
        const response = await axios({
            url: pollinationUrl,
            method: 'GET',
            responseType: 'stream',
            timeout: 10000
        });
        
        const writer = fs.createWriteStream(outputPath);
        response.data.pipe(writer);
        
        return new Promise((resolve, reject) => {
            writer.on('finish', () => resolve(true));
            writer.on('error', reject);
        });
    } catch (pollinationError) {
        console.error('Pollinations failed, using local static placeholder:', pollinationError.message);
        const staticPlaceholder = path.join(__dirname, '../public/assets/placeholder.jpg');
        if (fs.existsSync(staticPlaceholder)) {
            fs.copyFileSync(staticPlaceholder, outputPath);
        } else {
            fs.writeFileSync(outputPath, Buffer.from('dummy image content'));
        }
        return true;
    }
  }
}

/**
 * Evaluates the generated image using Gemini 1.5 Flash
 */
async function evaluateImage(prompt, generatedImagePath, referenceImagePath) {
  const ai = getNextClient();
  
  const evaluationPrompt = `
    You are an expert design judge. You are given a generated image and a target reference image.
    Your task is to score how closely the generated image matches the reference image in terms of:
    1. Visual composition and layout.
    2. Color palette and lighting.
    3. Objects, subjects, and their details.
    
    The original prompt was: "${prompt}".
    
    Assign a score from 0 to 100, where 100 is a near-perfect visual match.
    Return ONLY a JSON object: {"score": <number 0-100>}
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-1.5-flash-8b',
      contents: [
        {
          role: 'user',
          parts: [
            { text: evaluationPrompt },
            fileToGenerativePart(generatedImagePath, "image/jpeg"),
            fileToGenerativePart(referenceImagePath, "image/jpeg")
          ]
        }
      ],
      config: {
        responseMimeType: "application/json"
      }
    });

    const result = JSON.parse(response.candidates[0].content.parts[0].text);
    return Math.max(0, Math.min(100, result.score || 50));
  } catch (error) {
    console.error('Gemini evaluation failed:', error.message);
    return 50; // Fallback score
  }
}

module.exports = {
  generateImage,
  evaluateImage
};
