const { GoogleGenAI } = require('@google/genai');
const fs = require('fs');
const path = require('path');
const axios = require('axios'); // For placeholder generation if needed
const https = require('https');

// We have 3 keys for rotation
const apiKeys = [
  process.env.GEMINI_API_KEY_1,
  process.env.GEMINI_API_KEY_2,
  process.env.GEMINI_API_KEY_3
].filter(Boolean);

let currentKeyIndex = 0;

function getNextClient() {
  if (apiKeys.length === 0) {
    throw new Error('No Gemini API keys found in environment variables.');
  }
  const key = apiKeys[currentKeyIndex];
  currentKeyIndex = (currentKeyIndex + 1) % apiKeys.length;
  // Initialize SDK
  return new GoogleGenAI({ apiKey: key });
}

// Convert local file to generative part
function fileToGenerativePart(filePath, mimeType) {
  return {
    inlineData: {
      data: Buffer.from(fs.readFileSync(filePath)).toString("base64"),
      mimeType
    },
  };
}

async function generateImage(prompt, outputPath) {
  try {
    const ai = getNextClient();
    // Use Imagen 3.0 via Gemini API (if available on the key)
    const response = await ai.models.generateImages({
        model: 'imagen-3.0-generate-001',
        prompt: prompt,
        config: {
            numberOfImages: 1,
            outputMimeType: 'image/jpeg',
        }
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
        const base64Image = response.generatedImages[0].image.imageBytes;
        fs.writeFileSync(outputPath, Buffer.from(base64Image, 'base64'));
        return true;
    } else {
        throw new Error('No image generated by Gemini.');
    }
  } catch (error) {
    console.error('Gemini image generation failed, falling back to placeholder...', error.message);
    // Fallback: Using a free, unauthenticated text-to-image API just to keep the competition running if Imagen is not enabled on the provided keys.
    try {
        const encodedPrompt = encodeURIComponent(prompt);
        const fallbackUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?nologo=true`;
        const agent = new https.Agent({ rejectUnauthorized: false });
        const res = await axios.get(fallbackUrl, { responseType: 'arraybuffer', httpsAgent: agent });
        fs.writeFileSync(outputPath, Buffer.from(res.data, 'binary'));
        return true;
    } catch (fallbackError) {
        console.error('Fallback image generation failed:', fallbackError);
        throw new Error('Image generation failed completely.');
    }
  }
}

async function evaluateImage(prompt, generatedImagePath, referenceImagePath) {
  const ai = getNextClient();
  
  const generatedImagePart = fileToGenerativePart(generatedImagePath, "image/jpeg");
  const referenceImagePart = fileToGenerativePart(referenceImagePath, "image/jpeg");

  const evaluationPrompt = `
    You are an expert AI judge evaluating a competition. 
    You are given two images: 
    Image 1: The generated image.
    Image 2: The reference image.
    The user's prompt was: "${prompt}".
    
    Evaluate the generated image against the reference image and the prompt.
    Consider: Visual similarity, prompt quality, detail matching, and creativity.
    
    You MUST return ONLY a JSON object in the exact following format, with a score between 0 and 100. Do not use markdown blocks, just the raw JSON:
    {
      "score": <number>
    }
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash', // Using flash for speed, or pro if needed
      contents: [
        evaluationPrompt,
        generatedImagePart,
        referenceImagePart
      ],
      config: {
          responseMimeType: "application/json",
      }
    });
    
    const text = response.text;
    const jsonStr = text.replace(/```json/g, '').replace(/```/g, '').trim();
    const result = JSON.parse(jsonStr);
    
    // Ensure it's a number between 0 and 100
    let score = result.score || 0;
    score = Math.max(0, Math.min(100, Number(score)));
    
    return score;
  } catch (error) {
    console.error('Evaluation failed:', error);
    return 50; // Fallback score
  }
}

module.exports = {
  generateImage,
  evaluateImage
};
